### ISSUE TITLE
[Development] Make release page

### ISSUE THREAD

**Issue by josephj** [josephj/ignition-toolbelt#10]
.github/workflows/release.yml

```
name: Package and Release

on:
  push:
    tags:
      - 'v*' # This workflow triggers on push events to tags with 'v' prefix, e.g., v1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # If you have any build steps that require npm dependencies

      - name: Build extension
        run: npm run build # Replace this with your actual build command

      - name: Package extension into a zip file
        run: |
          zip -r release.zip dist/ # Replace 'dist/' with the directory containing your built extension files

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates this secret to authenticate in your workflow
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'Description of the release'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This is the URL for uploading assets to the release
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip

```

```
git tag v1.0.0
git push origin v1.0.0
```

Yes, GitHub can host your releases for free. GitHub allows you to create releases associated with a Git tag and upload binary files (such as compiled executables, minified scripts, documentation, etc.) as assets for each release.

When you create a release in your GitHub repository, you can attach any number of binary files, source code zips, and other assets without any cost. However, GitHub does have some usage limits:

Repository Size Limit: While GitHub doesn't have a strict limit on each repository's total size, they recommend keeping repositories under 1GB to ensure optimal performance. If your repository exceeds 5GB, you may receive an email from GitHub Support requesting that you reduce the size.

Release Asset Limit: Each release asset can be up to 2GB in size.

Bandwidth Limit: GitHub doesn't charge for bandwidth for cloning and fetching repositories within reasonable usage levels. However, if a repository generates an excessive amount of traffic, GitHub may reach out to the repository owner to discuss options.

For most users and projects, these limits are more than sufficient, and you can host your releases on GitHub without worrying about costs. It's a common practice to use GitHub Releases for distributing software, sharing executables, and providing package downloads associated with specific versions of your code.

Keep in mind that if you're working on a public, open-source project, all your releases and assets will be publicly available for anyone to download. If your project is private, then only collaborators or people with access to the repository will be able to download the release assets.

For more information, you can refer to GitHub's documentation on releases: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

Always make sure to comply with GitHub's terms of service and use the platform responsibly.
